package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Njuser;
import org.linlinjava.litemall.db.domain.NjuserExample;

public interface NjuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    long countByExample(NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int deleteByExample(NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int insert(Njuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int insertSelective(Njuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    Njuser selectOneByExample(NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    Njuser selectOneByExampleSelective(@Param("example") NjuserExample example, @Param("selective") Njuser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    List<Njuser> selectByExampleSelective(@Param("example") NjuserExample example, @Param("selective") Njuser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    List<Njuser> selectByExample(NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    Njuser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Njuser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    Njuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Njuser record, @Param("example") NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Njuser record, @Param("example") NjuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Njuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table njuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Njuser record);
}