package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Ruser;
import org.linlinjava.litemall.db.domain.RuserExample;

public interface RuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    long countByExample(RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int deleteByExample(RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int insert(Ruser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int insertSelective(Ruser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    Ruser selectOneByExample(RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    Ruser selectOneByExampleSelective(@Param("example") RuserExample example, @Param("selective") Ruser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    List<Ruser> selectByExampleSelective(@Param("example") RuserExample example, @Param("selective") Ruser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    List<Ruser> selectByExample(RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    Ruser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Ruser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    Ruser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Ruser record, @Param("example") RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Ruser record, @Param("example") RuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ruser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ruser record);
}