package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SchoolUser;
import org.linlinjava.litemall.db.domain.SchoolUserExample;

public interface SchoolUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    long countByExample(SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int insert(SchoolUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int insertSelective(SchoolUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    SchoolUser selectOneByExample(SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    SchoolUser selectOneByExampleSelective(@Param("example") SchoolUserExample example, @Param("selective") SchoolUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    List<SchoolUser> selectByExampleSelective(@Param("example") SchoolUserExample example, @Param("selective") SchoolUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    List<SchoolUser> selectByExample(SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    SchoolUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SchoolUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    SchoolUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolUser record, @Param("example") SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolUser record, @Param("example") SchoolUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchoolUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchoolUser record);
}