package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Userimportinfo;
import org.linlinjava.litemall.db.domain.UserimportinfoExample;

public interface UserimportinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    long countByExample(UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int deleteByExample(UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int insert(Userimportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int insertSelective(Userimportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    Userimportinfo selectOneByExample(UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    Userimportinfo selectOneByExampleSelective(@Param("example") UserimportinfoExample example, @Param("selective") Userimportinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    List<Userimportinfo> selectByExampleSelective(@Param("example") UserimportinfoExample example, @Param("selective") Userimportinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    List<Userimportinfo> selectByExample(UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    Userimportinfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Userimportinfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    Userimportinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Userimportinfo record, @Param("example") UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Userimportinfo record, @Param("example") UserimportinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Userimportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userimportinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userimportinfo record);
}