package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Usersign;
import org.linlinjava.litemall.db.domain.UsersignExample;

public interface UsersignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    long countByExample(UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int deleteByExample(UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int insert(Usersign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int insertSelective(Usersign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    Usersign selectOneByExample(UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    Usersign selectOneByExampleSelective(@Param("example") UsersignExample example, @Param("selective") Usersign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    List<Usersign> selectByExampleSelective(@Param("example") UsersignExample example, @Param("selective") Usersign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    List<Usersign> selectByExample(UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    Usersign selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Usersign.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    Usersign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usersign record, @Param("example") UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usersign record, @Param("example") UsersignExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usersign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersign
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usersign record);
}