package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Usertranster;
import org.linlinjava.litemall.db.domain.UsertransterExample;

public interface UsertransterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    long countByExample(UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int deleteByExample(UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int insert(Usertranster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int insertSelective(Usertranster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    Usertranster selectOneByExample(UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    Usertranster selectOneByExampleSelective(@Param("example") UsertransterExample example, @Param("selective") Usertranster.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    List<Usertranster> selectByExampleSelective(@Param("example") UsertransterExample example, @Param("selective") Usertranster.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    List<Usertranster> selectByExample(UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    Usertranster selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Usertranster.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    Usertranster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Usertranster record, @Param("example") UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Usertranster record, @Param("example") UsertransterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Usertranster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Usertranster record);
}