package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class BaseNanjing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.streets
     *
     * @mbg.generated
     */
    private String streets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_nanjing.communitys
     *
     * @mbg.generated
     */
    private String communitys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.id
     *
     * @return the value of base_nanjing.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.id
     *
     * @param id the value for base_nanjing.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.province_name
     *
     * @return the value of base_nanjing.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.province_name
     *
     * @param provinceName the value for base_nanjing.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.city_name
     *
     * @return the value of base_nanjing.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.city_name
     *
     * @param cityName the value for base_nanjing.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.area
     *
     * @return the value of base_nanjing.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.area
     *
     * @param area the value for base_nanjing.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.streets
     *
     * @return the value of base_nanjing.streets
     *
     * @mbg.generated
     */
    public String getStreets() {
        return streets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.streets
     *
     * @param streets the value for base_nanjing.streets
     *
     * @mbg.generated
     */
    public void setStreets(String streets) {
        this.streets = streets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_nanjing.communitys
     *
     * @return the value of base_nanjing.communitys
     *
     * @mbg.generated
     */
    public String getCommunitys() {
        return communitys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_nanjing.communitys
     *
     * @param communitys the value for base_nanjing.communitys
     *
     * @mbg.generated
     */
    public void setCommunitys(String communitys) {
        this.communitys = communitys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_nanjing
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityName=").append(cityName);
        sb.append(", area=").append(area);
        sb.append(", streets=").append(streets);
        sb.append(", communitys=").append(communitys);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_nanjing
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BaseNanjing other = (BaseNanjing) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProvinceName() == null ? other.getProvinceName() == null : this.getProvinceName().equals(other.getProvinceName()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getStreets() == null ? other.getStreets() == null : this.getStreets().equals(other.getStreets()))
            && (this.getCommunitys() == null ? other.getCommunitys() == null : this.getCommunitys().equals(other.getCommunitys()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_nanjing
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProvinceName() == null) ? 0 : getProvinceName().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getStreets() == null) ? 0 : getStreets().hashCode());
        result = prime * result + ((getCommunitys() == null) ? 0 : getCommunitys().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table base_nanjing
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        provinceName("province_name", "provinceName", "CHAR", false),
        cityName("city_name", "cityName", "CHAR", false),
        area("area", "area", "CHAR", false),
        streets("streets", "streets", "CHAR", false),
        communitys("communitys", "communitys", "CHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table base_nanjing
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}