package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Outsideuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.community
     *
     * @mbg.generated
     */
    private String community;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.liveaddress
     *
     * @mbg.generated
     */
    private String liveaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.arrivedate
     *
     * @mbg.generated
     */
    private LocalDateTime arrivedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.ifwh
     *
     * @mbg.generated
     */
    private String ifwh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.whtime
     *
     * @mbg.generated
     */
    private String whtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.livetype
     *
     * @mbg.generated
     */
    private String livetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.addtime
     *
     * @mbg.generated
     */
    private LocalDateTime addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.modifytime
     *
     * @mbg.generated
     */
    private LocalDateTime modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.ifgoout
     *
     * @mbg.generated
     */
    private String ifgoout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.goaddress
     *
     * @mbg.generated
     */
    private String goaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.other
     *
     * @mbg.generated
     */
    private String other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.iftouch
     *
     * @mbg.generated
     */
    private String iftouch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsideuser.street
     *
     * @mbg.generated
     */
    private String street;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.id
     *
     * @return the value of outsideuser.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.id
     *
     * @param id the value for outsideuser.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.name
     *
     * @return the value of outsideuser.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.name
     *
     * @param name the value for outsideuser.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.phone
     *
     * @return the value of outsideuser.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.phone
     *
     * @param phone the value for outsideuser.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.idcard
     *
     * @return the value of outsideuser.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.idcard
     *
     * @param idcard the value for outsideuser.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.sex
     *
     * @return the value of outsideuser.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.sex
     *
     * @param sex the value for outsideuser.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.age
     *
     * @return the value of outsideuser.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.age
     *
     * @param age the value for outsideuser.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.birthday
     *
     * @return the value of outsideuser.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.birthday
     *
     * @param birthday the value for outsideuser.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.community
     *
     * @return the value of outsideuser.community
     *
     * @mbg.generated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.community
     *
     * @param community the value for outsideuser.community
     *
     * @mbg.generated
     */
    public void setCommunity(String community) {
        this.community = community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.liveaddress
     *
     * @return the value of outsideuser.liveaddress
     *
     * @mbg.generated
     */
    public String getLiveaddress() {
        return liveaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.liveaddress
     *
     * @param liveaddress the value for outsideuser.liveaddress
     *
     * @mbg.generated
     */
    public void setLiveaddress(String liveaddress) {
        this.liveaddress = liveaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.arrivedate
     *
     * @return the value of outsideuser.arrivedate
     *
     * @mbg.generated
     */
    public LocalDateTime getArrivedate() {
        return arrivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.arrivedate
     *
     * @param arrivedate the value for outsideuser.arrivedate
     *
     * @mbg.generated
     */
    public void setArrivedate(LocalDateTime arrivedate) {
        this.arrivedate = arrivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.province
     *
     * @return the value of outsideuser.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.province
     *
     * @param province the value for outsideuser.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.city
     *
     * @return the value of outsideuser.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.city
     *
     * @param city the value for outsideuser.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.district
     *
     * @return the value of outsideuser.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.district
     *
     * @param district the value for outsideuser.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.ifwh
     *
     * @return the value of outsideuser.ifwh
     *
     * @mbg.generated
     */
    public String getIfwh() {
        return ifwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.ifwh
     *
     * @param ifwh the value for outsideuser.ifwh
     *
     * @mbg.generated
     */
    public void setIfwh(String ifwh) {
        this.ifwh = ifwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.whtime
     *
     * @return the value of outsideuser.whtime
     *
     * @mbg.generated
     */
    public String getWhtime() {
        return whtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.whtime
     *
     * @param whtime the value for outsideuser.whtime
     *
     * @mbg.generated
     */
    public void setWhtime(String whtime) {
        this.whtime = whtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.livetype
     *
     * @return the value of outsideuser.livetype
     *
     * @mbg.generated
     */
    public String getLivetype() {
        return livetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.livetype
     *
     * @param livetype the value for outsideuser.livetype
     *
     * @mbg.generated
     */
    public void setLivetype(String livetype) {
        this.livetype = livetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.remark
     *
     * @return the value of outsideuser.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.remark
     *
     * @param remark the value for outsideuser.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.addtime
     *
     * @return the value of outsideuser.addtime
     *
     * @mbg.generated
     */
    public LocalDateTime getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.addtime
     *
     * @param addtime the value for outsideuser.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(LocalDateTime addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.modifytime
     *
     * @return the value of outsideuser.modifytime
     *
     * @mbg.generated
     */
    public LocalDateTime getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.modifytime
     *
     * @param modifytime the value for outsideuser.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(LocalDateTime modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.ifgoout
     *
     * @return the value of outsideuser.ifgoout
     *
     * @mbg.generated
     */
    public String getIfgoout() {
        return ifgoout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.ifgoout
     *
     * @param ifgoout the value for outsideuser.ifgoout
     *
     * @mbg.generated
     */
    public void setIfgoout(String ifgoout) {
        this.ifgoout = ifgoout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.goaddress
     *
     * @return the value of outsideuser.goaddress
     *
     * @mbg.generated
     */
    public String getGoaddress() {
        return goaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.goaddress
     *
     * @param goaddress the value for outsideuser.goaddress
     *
     * @mbg.generated
     */
    public void setGoaddress(String goaddress) {
        this.goaddress = goaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.other
     *
     * @return the value of outsideuser.other
     *
     * @mbg.generated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.other
     *
     * @param other the value for outsideuser.other
     *
     * @mbg.generated
     */
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.iftouch
     *
     * @return the value of outsideuser.iftouch
     *
     * @mbg.generated
     */
    public String getIftouch() {
        return iftouch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.iftouch
     *
     * @param iftouch the value for outsideuser.iftouch
     *
     * @mbg.generated
     */
    public void setIftouch(String iftouch) {
        this.iftouch = iftouch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.area
     *
     * @return the value of outsideuser.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.area
     *
     * @param area the value for outsideuser.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsideuser.street
     *
     * @return the value of outsideuser.street
     *
     * @mbg.generated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsideuser.street
     *
     * @param street the value for outsideuser.street
     *
     * @mbg.generated
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outsideuser
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", idcard=").append(idcard);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", birthday=").append(birthday);
        sb.append(", community=").append(community);
        sb.append(", liveaddress=").append(liveaddress);
        sb.append(", arrivedate=").append(arrivedate);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", ifwh=").append(ifwh);
        sb.append(", whtime=").append(whtime);
        sb.append(", livetype=").append(livetype);
        sb.append(", remark=").append(remark);
        sb.append(", addtime=").append(addtime);
        sb.append(", modifytime=").append(modifytime);
        sb.append(", ifgoout=").append(ifgoout);
        sb.append(", goaddress=").append(goaddress);
        sb.append(", other=").append(other);
        sb.append(", iftouch=").append(iftouch);
        sb.append(", area=").append(area);
        sb.append(", street=").append(street);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outsideuser
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Outsideuser other = (Outsideuser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getCommunity() == null ? other.getCommunity() == null : this.getCommunity().equals(other.getCommunity()))
            && (this.getLiveaddress() == null ? other.getLiveaddress() == null : this.getLiveaddress().equals(other.getLiveaddress()))
            && (this.getArrivedate() == null ? other.getArrivedate() == null : this.getArrivedate().equals(other.getArrivedate()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getIfwh() == null ? other.getIfwh() == null : this.getIfwh().equals(other.getIfwh()))
            && (this.getWhtime() == null ? other.getWhtime() == null : this.getWhtime().equals(other.getWhtime()))
            && (this.getLivetype() == null ? other.getLivetype() == null : this.getLivetype().equals(other.getLivetype()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getAddtime() == null ? other.getAddtime() == null : this.getAddtime().equals(other.getAddtime()))
            && (this.getModifytime() == null ? other.getModifytime() == null : this.getModifytime().equals(other.getModifytime()))
            && (this.getIfgoout() == null ? other.getIfgoout() == null : this.getIfgoout().equals(other.getIfgoout()))
            && (this.getGoaddress() == null ? other.getGoaddress() == null : this.getGoaddress().equals(other.getGoaddress()))
            && (this.getOther() == null ? other.getOther() == null : this.getOther().equals(other.getOther()))
            && (this.getIftouch() == null ? other.getIftouch() == null : this.getIftouch().equals(other.getIftouch()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getStreet() == null ? other.getStreet() == null : this.getStreet().equals(other.getStreet()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outsideuser
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getCommunity() == null) ? 0 : getCommunity().hashCode());
        result = prime * result + ((getLiveaddress() == null) ? 0 : getLiveaddress().hashCode());
        result = prime * result + ((getArrivedate() == null) ? 0 : getArrivedate().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getIfwh() == null) ? 0 : getIfwh().hashCode());
        result = prime * result + ((getWhtime() == null) ? 0 : getWhtime().hashCode());
        result = prime * result + ((getLivetype() == null) ? 0 : getLivetype().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getAddtime() == null) ? 0 : getAddtime().hashCode());
        result = prime * result + ((getModifytime() == null) ? 0 : getModifytime().hashCode());
        result = prime * result + ((getIfgoout() == null) ? 0 : getIfgoout().hashCode());
        result = prime * result + ((getGoaddress() == null) ? 0 : getGoaddress().hashCode());
        result = prime * result + ((getOther() == null) ? 0 : getOther().hashCode());
        result = prime * result + ((getIftouch() == null) ? 0 : getIftouch().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getStreet() == null) ? 0 : getStreet().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table outsideuser
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        phone("phone", "phone", "VARCHAR", false),
        idcard("idcard", "idcard", "VARCHAR", false),
        sex("sex", "sex", "VARCHAR", false),
        age("age", "age", "INTEGER", false),
        birthday("birthday", "birthday", "VARCHAR", false),
        community("community", "community", "VARCHAR", false),
        liveaddress("liveaddress", "liveaddress", "VARCHAR", false),
        arrivedate("arrivedate", "arrivedate", "TIMESTAMP", false),
        province("province", "province", "VARCHAR", false),
        city("city", "city", "VARCHAR", false),
        district("district", "district", "VARCHAR", false),
        ifwh("ifwh", "ifwh", "VARCHAR", false),
        whtime("whtime", "whtime", "VARCHAR", false),
        livetype("livetype", "livetype", "VARCHAR", false),
        remark("remark", "remark", "VARCHAR", false),
        addtime("addtime", "addtime", "TIMESTAMP", false),
        modifytime("modifytime", "modifytime", "TIMESTAMP", false),
        ifgoout("ifgoout", "ifgoout", "VARCHAR", false),
        goaddress("goaddress", "goaddress", "VARCHAR", false),
        other("other", "other", "VARCHAR", false),
        iftouch("iftouch", "iftouch", "VARCHAR", false),
        area("area", "area", "VARCHAR", false),
        street("street", "street", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table outsideuser
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}