package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class Ruser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a1
     *
     * @mbg.generated
     */
    private String a1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a2
     *
     * @mbg.generated
     */
    private String a2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a3
     *
     * @mbg.generated
     */
    private String a3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a4
     *
     * @mbg.generated
     */
    private String a4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a5
     *
     * @mbg.generated
     */
    private String a5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a6
     *
     * @mbg.generated
     */
    private String a6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a7
     *
     * @mbg.generated
     */
    private String a7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a8
     *
     * @mbg.generated
     */
    private String a8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a9
     *
     * @mbg.generated
     */
    private String a9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a10
     *
     * @mbg.generated
     */
    private String a10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a11
     *
     * @mbg.generated
     */
    private String a11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a12
     *
     * @mbg.generated
     */
    private String a12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a13
     *
     * @mbg.generated
     */
    private String a13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a14
     *
     * @mbg.generated
     */
    private String a14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a15
     *
     * @mbg.generated
     */
    private String a15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a16
     *
     * @mbg.generated
     */
    private String a16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a17
     *
     * @mbg.generated
     */
    private String a17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a18
     *
     * @mbg.generated
     */
    private String a18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a19
     *
     * @mbg.generated
     */
    private String a19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a20
     *
     * @mbg.generated
     */
    private String a20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a21
     *
     * @mbg.generated
     */
    private String a21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a22
     *
     * @mbg.generated
     */
    private String a22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a23
     *
     * @mbg.generated
     */
    private String a23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a24
     *
     * @mbg.generated
     */
    private String a24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a25
     *
     * @mbg.generated
     */
    private String a25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a26
     *
     * @mbg.generated
     */
    private String a26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a27
     *
     * @mbg.generated
     */
    private String a27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a28
     *
     * @mbg.generated
     */
    private String a28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a29
     *
     * @mbg.generated
     */
    private String a29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruser.a30
     *
     * @mbg.generated
     */
    private String a30;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.id
     *
     * @return the value of ruser.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.id
     *
     * @param id the value for ruser.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a1
     *
     * @return the value of ruser.a1
     *
     * @mbg.generated
     */
    public String getA1() {
        return a1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a1
     *
     * @param a1 the value for ruser.a1
     *
     * @mbg.generated
     */
    public void setA1(String a1) {
        this.a1 = a1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a2
     *
     * @return the value of ruser.a2
     *
     * @mbg.generated
     */
    public String getA2() {
        return a2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a2
     *
     * @param a2 the value for ruser.a2
     *
     * @mbg.generated
     */
    public void setA2(String a2) {
        this.a2 = a2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a3
     *
     * @return the value of ruser.a3
     *
     * @mbg.generated
     */
    public String getA3() {
        return a3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a3
     *
     * @param a3 the value for ruser.a3
     *
     * @mbg.generated
     */
    public void setA3(String a3) {
        this.a3 = a3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a4
     *
     * @return the value of ruser.a4
     *
     * @mbg.generated
     */
    public String getA4() {
        return a4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a4
     *
     * @param a4 the value for ruser.a4
     *
     * @mbg.generated
     */
    public void setA4(String a4) {
        this.a4 = a4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a5
     *
     * @return the value of ruser.a5
     *
     * @mbg.generated
     */
    public String getA5() {
        return a5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a5
     *
     * @param a5 the value for ruser.a5
     *
     * @mbg.generated
     */
    public void setA5(String a5) {
        this.a5 = a5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a6
     *
     * @return the value of ruser.a6
     *
     * @mbg.generated
     */
    public String getA6() {
        return a6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a6
     *
     * @param a6 the value for ruser.a6
     *
     * @mbg.generated
     */
    public void setA6(String a6) {
        this.a6 = a6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a7
     *
     * @return the value of ruser.a7
     *
     * @mbg.generated
     */
    public String getA7() {
        return a7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a7
     *
     * @param a7 the value for ruser.a7
     *
     * @mbg.generated
     */
    public void setA7(String a7) {
        this.a7 = a7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a8
     *
     * @return the value of ruser.a8
     *
     * @mbg.generated
     */
    public String getA8() {
        return a8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a8
     *
     * @param a8 the value for ruser.a8
     *
     * @mbg.generated
     */
    public void setA8(String a8) {
        this.a8 = a8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a9
     *
     * @return the value of ruser.a9
     *
     * @mbg.generated
     */
    public String getA9() {
        return a9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a9
     *
     * @param a9 the value for ruser.a9
     *
     * @mbg.generated
     */
    public void setA9(String a9) {
        this.a9 = a9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a10
     *
     * @return the value of ruser.a10
     *
     * @mbg.generated
     */
    public String getA10() {
        return a10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a10
     *
     * @param a10 the value for ruser.a10
     *
     * @mbg.generated
     */
    public void setA10(String a10) {
        this.a10 = a10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a11
     *
     * @return the value of ruser.a11
     *
     * @mbg.generated
     */
    public String getA11() {
        return a11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a11
     *
     * @param a11 the value for ruser.a11
     *
     * @mbg.generated
     */
    public void setA11(String a11) {
        this.a11 = a11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a12
     *
     * @return the value of ruser.a12
     *
     * @mbg.generated
     */
    public String getA12() {
        return a12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a12
     *
     * @param a12 the value for ruser.a12
     *
     * @mbg.generated
     */
    public void setA12(String a12) {
        this.a12 = a12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a13
     *
     * @return the value of ruser.a13
     *
     * @mbg.generated
     */
    public String getA13() {
        return a13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a13
     *
     * @param a13 the value for ruser.a13
     *
     * @mbg.generated
     */
    public void setA13(String a13) {
        this.a13 = a13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a14
     *
     * @return the value of ruser.a14
     *
     * @mbg.generated
     */
    public String getA14() {
        return a14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a14
     *
     * @param a14 the value for ruser.a14
     *
     * @mbg.generated
     */
    public void setA14(String a14) {
        this.a14 = a14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a15
     *
     * @return the value of ruser.a15
     *
     * @mbg.generated
     */
    public String getA15() {
        return a15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a15
     *
     * @param a15 the value for ruser.a15
     *
     * @mbg.generated
     */
    public void setA15(String a15) {
        this.a15 = a15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a16
     *
     * @return the value of ruser.a16
     *
     * @mbg.generated
     */
    public String getA16() {
        return a16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a16
     *
     * @param a16 the value for ruser.a16
     *
     * @mbg.generated
     */
    public void setA16(String a16) {
        this.a16 = a16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a17
     *
     * @return the value of ruser.a17
     *
     * @mbg.generated
     */
    public String getA17() {
        return a17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a17
     *
     * @param a17 the value for ruser.a17
     *
     * @mbg.generated
     */
    public void setA17(String a17) {
        this.a17 = a17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a18
     *
     * @return the value of ruser.a18
     *
     * @mbg.generated
     */
    public String getA18() {
        return a18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a18
     *
     * @param a18 the value for ruser.a18
     *
     * @mbg.generated
     */
    public void setA18(String a18) {
        this.a18 = a18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a19
     *
     * @return the value of ruser.a19
     *
     * @mbg.generated
     */
    public String getA19() {
        return a19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a19
     *
     * @param a19 the value for ruser.a19
     *
     * @mbg.generated
     */
    public void setA19(String a19) {
        this.a19 = a19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a20
     *
     * @return the value of ruser.a20
     *
     * @mbg.generated
     */
    public String getA20() {
        return a20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a20
     *
     * @param a20 the value for ruser.a20
     *
     * @mbg.generated
     */
    public void setA20(String a20) {
        this.a20 = a20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a21
     *
     * @return the value of ruser.a21
     *
     * @mbg.generated
     */
    public String getA21() {
        return a21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a21
     *
     * @param a21 the value for ruser.a21
     *
     * @mbg.generated
     */
    public void setA21(String a21) {
        this.a21 = a21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a22
     *
     * @return the value of ruser.a22
     *
     * @mbg.generated
     */
    public String getA22() {
        return a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a22
     *
     * @param a22 the value for ruser.a22
     *
     * @mbg.generated
     */
    public void setA22(String a22) {
        this.a22 = a22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a23
     *
     * @return the value of ruser.a23
     *
     * @mbg.generated
     */
    public String getA23() {
        return a23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a23
     *
     * @param a23 the value for ruser.a23
     *
     * @mbg.generated
     */
    public void setA23(String a23) {
        this.a23 = a23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a24
     *
     * @return the value of ruser.a24
     *
     * @mbg.generated
     */
    public String getA24() {
        return a24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a24
     *
     * @param a24 the value for ruser.a24
     *
     * @mbg.generated
     */
    public void setA24(String a24) {
        this.a24 = a24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a25
     *
     * @return the value of ruser.a25
     *
     * @mbg.generated
     */
    public String getA25() {
        return a25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a25
     *
     * @param a25 the value for ruser.a25
     *
     * @mbg.generated
     */
    public void setA25(String a25) {
        this.a25 = a25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a26
     *
     * @return the value of ruser.a26
     *
     * @mbg.generated
     */
    public String getA26() {
        return a26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a26
     *
     * @param a26 the value for ruser.a26
     *
     * @mbg.generated
     */
    public void setA26(String a26) {
        this.a26 = a26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a27
     *
     * @return the value of ruser.a27
     *
     * @mbg.generated
     */
    public String getA27() {
        return a27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a27
     *
     * @param a27 the value for ruser.a27
     *
     * @mbg.generated
     */
    public void setA27(String a27) {
        this.a27 = a27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a28
     *
     * @return the value of ruser.a28
     *
     * @mbg.generated
     */
    public String getA28() {
        return a28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a28
     *
     * @param a28 the value for ruser.a28
     *
     * @mbg.generated
     */
    public void setA28(String a28) {
        this.a28 = a28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a29
     *
     * @return the value of ruser.a29
     *
     * @mbg.generated
     */
    public String getA29() {
        return a29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a29
     *
     * @param a29 the value for ruser.a29
     *
     * @mbg.generated
     */
    public void setA29(String a29) {
        this.a29 = a29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruser.a30
     *
     * @return the value of ruser.a30
     *
     * @mbg.generated
     */
    public String getA30() {
        return a30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruser.a30
     *
     * @param a30 the value for ruser.a30
     *
     * @mbg.generated
     */
    public void setA30(String a30) {
        this.a30 = a30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", a1=").append(a1);
        sb.append(", a2=").append(a2);
        sb.append(", a3=").append(a3);
        sb.append(", a4=").append(a4);
        sb.append(", a5=").append(a5);
        sb.append(", a6=").append(a6);
        sb.append(", a7=").append(a7);
        sb.append(", a8=").append(a8);
        sb.append(", a9=").append(a9);
        sb.append(", a10=").append(a10);
        sb.append(", a11=").append(a11);
        sb.append(", a12=").append(a12);
        sb.append(", a13=").append(a13);
        sb.append(", a14=").append(a14);
        sb.append(", a15=").append(a15);
        sb.append(", a16=").append(a16);
        sb.append(", a17=").append(a17);
        sb.append(", a18=").append(a18);
        sb.append(", a19=").append(a19);
        sb.append(", a20=").append(a20);
        sb.append(", a21=").append(a21);
        sb.append(", a22=").append(a22);
        sb.append(", a23=").append(a23);
        sb.append(", a24=").append(a24);
        sb.append(", a25=").append(a25);
        sb.append(", a26=").append(a26);
        sb.append(", a27=").append(a27);
        sb.append(", a28=").append(a28);
        sb.append(", a29=").append(a29);
        sb.append(", a30=").append(a30);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Ruser other = (Ruser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getA1() == null ? other.getA1() == null : this.getA1().equals(other.getA1()))
            && (this.getA2() == null ? other.getA2() == null : this.getA2().equals(other.getA2()))
            && (this.getA3() == null ? other.getA3() == null : this.getA3().equals(other.getA3()))
            && (this.getA4() == null ? other.getA4() == null : this.getA4().equals(other.getA4()))
            && (this.getA5() == null ? other.getA5() == null : this.getA5().equals(other.getA5()))
            && (this.getA6() == null ? other.getA6() == null : this.getA6().equals(other.getA6()))
            && (this.getA7() == null ? other.getA7() == null : this.getA7().equals(other.getA7()))
            && (this.getA8() == null ? other.getA8() == null : this.getA8().equals(other.getA8()))
            && (this.getA9() == null ? other.getA9() == null : this.getA9().equals(other.getA9()))
            && (this.getA10() == null ? other.getA10() == null : this.getA10().equals(other.getA10()))
            && (this.getA11() == null ? other.getA11() == null : this.getA11().equals(other.getA11()))
            && (this.getA12() == null ? other.getA12() == null : this.getA12().equals(other.getA12()))
            && (this.getA13() == null ? other.getA13() == null : this.getA13().equals(other.getA13()))
            && (this.getA14() == null ? other.getA14() == null : this.getA14().equals(other.getA14()))
            && (this.getA15() == null ? other.getA15() == null : this.getA15().equals(other.getA15()))
            && (this.getA16() == null ? other.getA16() == null : this.getA16().equals(other.getA16()))
            && (this.getA17() == null ? other.getA17() == null : this.getA17().equals(other.getA17()))
            && (this.getA18() == null ? other.getA18() == null : this.getA18().equals(other.getA18()))
            && (this.getA19() == null ? other.getA19() == null : this.getA19().equals(other.getA19()))
            && (this.getA20() == null ? other.getA20() == null : this.getA20().equals(other.getA20()))
            && (this.getA21() == null ? other.getA21() == null : this.getA21().equals(other.getA21()))
            && (this.getA22() == null ? other.getA22() == null : this.getA22().equals(other.getA22()))
            && (this.getA23() == null ? other.getA23() == null : this.getA23().equals(other.getA23()))
            && (this.getA24() == null ? other.getA24() == null : this.getA24().equals(other.getA24()))
            && (this.getA25() == null ? other.getA25() == null : this.getA25().equals(other.getA25()))
            && (this.getA26() == null ? other.getA26() == null : this.getA26().equals(other.getA26()))
            && (this.getA27() == null ? other.getA27() == null : this.getA27().equals(other.getA27()))
            && (this.getA28() == null ? other.getA28() == null : this.getA28().equals(other.getA28()))
            && (this.getA29() == null ? other.getA29() == null : this.getA29().equals(other.getA29()))
            && (this.getA30() == null ? other.getA30() == null : this.getA30().equals(other.getA30()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruser
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getA1() == null) ? 0 : getA1().hashCode());
        result = prime * result + ((getA2() == null) ? 0 : getA2().hashCode());
        result = prime * result + ((getA3() == null) ? 0 : getA3().hashCode());
        result = prime * result + ((getA4() == null) ? 0 : getA4().hashCode());
        result = prime * result + ((getA5() == null) ? 0 : getA5().hashCode());
        result = prime * result + ((getA6() == null) ? 0 : getA6().hashCode());
        result = prime * result + ((getA7() == null) ? 0 : getA7().hashCode());
        result = prime * result + ((getA8() == null) ? 0 : getA8().hashCode());
        result = prime * result + ((getA9() == null) ? 0 : getA9().hashCode());
        result = prime * result + ((getA10() == null) ? 0 : getA10().hashCode());
        result = prime * result + ((getA11() == null) ? 0 : getA11().hashCode());
        result = prime * result + ((getA12() == null) ? 0 : getA12().hashCode());
        result = prime * result + ((getA13() == null) ? 0 : getA13().hashCode());
        result = prime * result + ((getA14() == null) ? 0 : getA14().hashCode());
        result = prime * result + ((getA15() == null) ? 0 : getA15().hashCode());
        result = prime * result + ((getA16() == null) ? 0 : getA16().hashCode());
        result = prime * result + ((getA17() == null) ? 0 : getA17().hashCode());
        result = prime * result + ((getA18() == null) ? 0 : getA18().hashCode());
        result = prime * result + ((getA19() == null) ? 0 : getA19().hashCode());
        result = prime * result + ((getA20() == null) ? 0 : getA20().hashCode());
        result = prime * result + ((getA21() == null) ? 0 : getA21().hashCode());
        result = prime * result + ((getA22() == null) ? 0 : getA22().hashCode());
        result = prime * result + ((getA23() == null) ? 0 : getA23().hashCode());
        result = prime * result + ((getA24() == null) ? 0 : getA24().hashCode());
        result = prime * result + ((getA25() == null) ? 0 : getA25().hashCode());
        result = prime * result + ((getA26() == null) ? 0 : getA26().hashCode());
        result = prime * result + ((getA27() == null) ? 0 : getA27().hashCode());
        result = prime * result + ((getA28() == null) ? 0 : getA28().hashCode());
        result = prime * result + ((getA29() == null) ? 0 : getA29().hashCode());
        result = prime * result + ((getA30() == null) ? 0 : getA30().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ruser
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        a1("a1", "a1", "VARCHAR", false),
        a2("a2", "a2", "VARCHAR", false),
        a3("a3", "a3", "VARCHAR", false),
        a4("a4", "a4", "VARCHAR", false),
        a5("a5", "a5", "VARCHAR", false),
        a6("a6", "a6", "VARCHAR", false),
        a7("a7", "a7", "VARCHAR", false),
        a8("a8", "a8", "VARCHAR", false),
        a9("a9", "a9", "VARCHAR", false),
        a10("a10", "a10", "VARCHAR", false),
        a11("a11", "a11", "VARCHAR", false),
        a12("a12", "a12", "VARCHAR", false),
        a13("a13", "a13", "VARCHAR", false),
        a14("a14", "a14", "VARCHAR", false),
        a15("a15", "a15", "VARCHAR", false),
        a16("a16", "a16", "VARCHAR", false),
        a17("a17", "a17", "VARCHAR", false),
        a18("a18", "a18", "VARCHAR", false),
        a19("a19", "a19", "VARCHAR", false),
        a20("a20", "a20", "VARCHAR", false),
        a21("a21", "a21", "VARCHAR", false),
        a22("a22", "a22", "VARCHAR", false),
        a23("a23", "a23", "VARCHAR", false),
        a24("a24", "a24", "VARCHAR", false),
        a25("a25", "a25", "VARCHAR", false),
        a26("a26", "a26", "VARCHAR", false),
        a27("a27", "a27", "VARCHAR", false),
        a28("a28", "a28", "VARCHAR", false),
        a29("a29", "a29", "VARCHAR", false),
        a30("a30", "a30", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table ruser
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table ruser
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}