package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class Usertranster {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.oarea
     *
     * @mbg.generated
     */
    private String oarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.ostreet
     *
     * @mbg.generated
     */
    private String ostreet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.ocommunity
     *
     * @mbg.generated
     */
    private String ocommunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.narea
     *
     * @mbg.generated
     */
    private String narea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.nstreet
     *
     * @mbg.generated
     */
    private String nstreet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.ncommunity
     *
     * @mbg.generated
     */
    private String ncommunity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertranster.addtime
     *
     * @mbg.generated
     */
    private LocalDateTime addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.id
     *
     * @return the value of usertranster.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.id
     *
     * @param id the value for usertranster.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.uid
     *
     * @return the value of usertranster.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.uid
     *
     * @param uid the value for usertranster.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.name
     *
     * @return the value of usertranster.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.name
     *
     * @param name the value for usertranster.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.sex
     *
     * @return the value of usertranster.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.sex
     *
     * @param sex the value for usertranster.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.age
     *
     * @return the value of usertranster.age
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.age
     *
     * @param age the value for usertranster.age
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.idcard
     *
     * @return the value of usertranster.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.idcard
     *
     * @param idcard the value for usertranster.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.oarea
     *
     * @return the value of usertranster.oarea
     *
     * @mbg.generated
     */
    public String getOarea() {
        return oarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.oarea
     *
     * @param oarea the value for usertranster.oarea
     *
     * @mbg.generated
     */
    public void setOarea(String oarea) {
        this.oarea = oarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.ostreet
     *
     * @return the value of usertranster.ostreet
     *
     * @mbg.generated
     */
    public String getOstreet() {
        return ostreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.ostreet
     *
     * @param ostreet the value for usertranster.ostreet
     *
     * @mbg.generated
     */
    public void setOstreet(String ostreet) {
        this.ostreet = ostreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.ocommunity
     *
     * @return the value of usertranster.ocommunity
     *
     * @mbg.generated
     */
    public String getOcommunity() {
        return ocommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.ocommunity
     *
     * @param ocommunity the value for usertranster.ocommunity
     *
     * @mbg.generated
     */
    public void setOcommunity(String ocommunity) {
        this.ocommunity = ocommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.narea
     *
     * @return the value of usertranster.narea
     *
     * @mbg.generated
     */
    public String getNarea() {
        return narea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.narea
     *
     * @param narea the value for usertranster.narea
     *
     * @mbg.generated
     */
    public void setNarea(String narea) {
        this.narea = narea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.nstreet
     *
     * @return the value of usertranster.nstreet
     *
     * @mbg.generated
     */
    public String getNstreet() {
        return nstreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.nstreet
     *
     * @param nstreet the value for usertranster.nstreet
     *
     * @mbg.generated
     */
    public void setNstreet(String nstreet) {
        this.nstreet = nstreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.ncommunity
     *
     * @return the value of usertranster.ncommunity
     *
     * @mbg.generated
     */
    public String getNcommunity() {
        return ncommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.ncommunity
     *
     * @param ncommunity the value for usertranster.ncommunity
     *
     * @mbg.generated
     */
    public void setNcommunity(String ncommunity) {
        this.ncommunity = ncommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.status
     *
     * @return the value of usertranster.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.status
     *
     * @param status the value for usertranster.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertranster.addtime
     *
     * @return the value of usertranster.addtime
     *
     * @mbg.generated
     */
    public LocalDateTime getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertranster.addtime
     *
     * @param addtime the value for usertranster.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(LocalDateTime addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", idcard=").append(idcard);
        sb.append(", oarea=").append(oarea);
        sb.append(", ostreet=").append(ostreet);
        sb.append(", ocommunity=").append(ocommunity);
        sb.append(", narea=").append(narea);
        sb.append(", nstreet=").append(nstreet);
        sb.append(", ncommunity=").append(ncommunity);
        sb.append(", status=").append(status);
        sb.append(", addtime=").append(addtime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Usertranster other = (Usertranster) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
            && (this.getOarea() == null ? other.getOarea() == null : this.getOarea().equals(other.getOarea()))
            && (this.getOstreet() == null ? other.getOstreet() == null : this.getOstreet().equals(other.getOstreet()))
            && (this.getOcommunity() == null ? other.getOcommunity() == null : this.getOcommunity().equals(other.getOcommunity()))
            && (this.getNarea() == null ? other.getNarea() == null : this.getNarea().equals(other.getNarea()))
            && (this.getNstreet() == null ? other.getNstreet() == null : this.getNstreet().equals(other.getNstreet()))
            && (this.getNcommunity() == null ? other.getNcommunity() == null : this.getNcommunity().equals(other.getNcommunity()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAddtime() == null ? other.getAddtime() == null : this.getAddtime().equals(other.getAddtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getOarea() == null) ? 0 : getOarea().hashCode());
        result = prime * result + ((getOstreet() == null) ? 0 : getOstreet().hashCode());
        result = prime * result + ((getOcommunity() == null) ? 0 : getOcommunity().hashCode());
        result = prime * result + ((getNarea() == null) ? 0 : getNarea().hashCode());
        result = prime * result + ((getNstreet() == null) ? 0 : getNstreet().hashCode());
        result = prime * result + ((getNcommunity() == null) ? 0 : getNcommunity().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAddtime() == null) ? 0 : getAddtime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table usertranster
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        uid("uid", "uid", "INTEGER", true),
        name("name", "name", "VARCHAR", true),
        sex("sex", "sex", "VARCHAR", false),
        age("age", "age", "VARCHAR", false),
        idcard("idcard", "idcard", "VARCHAR", false),
        oarea("oarea", "oarea", "VARCHAR", false),
        ostreet("ostreet", "ostreet", "VARCHAR", false),
        ocommunity("ocommunity", "ocommunity", "VARCHAR", false),
        narea("narea", "narea", "VARCHAR", false),
        nstreet("nstreet", "nstreet", "VARCHAR", false),
        ncommunity("ncommunity", "ncommunity", "VARCHAR", false),
        status("status", "status", "INTEGER", true),
        addtime("addtime", "addtime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table usertranster
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}